CREATE TABLE IF NOT EXISTS forum (
  title VARCHAR(256) NOT NULL,
  "user" VARCHAR(128) NOT NULL,
  slug VARCHAR(128) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS thread (
  id bigserial NOT NULL PRIMARY KEY,
  title VARCHAR(256) NOT NULL,
  author VARCHAR(128) NOT NULL,
  forumSlug VARCHAR(128) NOT NULL,
  slug VARCHAR(128) NOT NULL UNIQUE,
  "message" TEXT NOT NULL,
  votesCount INTEGER NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);

