// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/reo7sp/technopark-db/models"
)

// NewForumCreateParams creates a new ForumCreateParams object
// with the default values initialized.
func NewForumCreateParams() ForumCreateParams {
	var ()
	return ForumCreateParams{}
}

// ForumCreateParams contains all the bound params for the forum create operation
// typically these are obtained from a http.Request
//
// swagger:parameters forumCreate
type ForumCreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Данные форума.
	  Required: true
	  In: body
	*/
	Forum *models.Forum
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ForumCreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Forum
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("forum", "body"))
			} else {
				res = append(res, errors.NewParseError("forum", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Forum = &body
			}
		}

	} else {
		res = append(res, errors.Required("forum", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
