// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/reo7sp/technopark-db/models"
)

// NewUserUpdateParams creates a new UserUpdateParams object
// with the default values initialized.
func NewUserUpdateParams() UserUpdateParams {
	var ()
	return UserUpdateParams{}
}

// UserUpdateParams contains all the bound params for the user update operation
// typically these are obtained from a http.Request
//
// swagger:parameters userUpdate
type UserUpdateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Идентификатор пользователя.
	  Required: true
	  In: path
	*/
	Nickname string
	/*Изменения профиля пользователя.
	  Required: true
	  In: body
	*/
	Profile *models.UserUpdate
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UserUpdateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rNickname, rhkNickname, _ := route.Params.GetOK("nickname")
	if err := o.bindNickname(rNickname, rhkNickname, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UserUpdate
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("profile", "body"))
			} else {
				res = append(res, errors.NewParseError("profile", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Profile = &body
			}
		}

	} else {
		res = append(res, errors.Required("profile", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UserUpdateParams) bindNickname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Nickname = raw

	return nil
}
